name: flutter_craft
description: 完全采用Flutter开发的仿「雷霆战机」小游戏
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 0.1.2
  rxdart: 0.22.1
  soundpool: 0.5.3
  audioplayers: 0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/bg1.jpg
    - images/bg2.jpg
    - images/bullet.png
    - images/enemy01.png
    - images/enemy02.png
    - images/enemy03.png
    - images/player_bullet01.png
    - images/player_state1.png
    - images/player_state2.png
    - images/player_state3.png
    - images/player_state4.png
    - assets/game_bg.mp3
    - assets/player_bullet.wav