name: flutter_craft
description: 完全采用Flutter开发的仿「雷霆战机」小游戏
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 0.1.2
  rxdart: 0.22.1
  soundpool: 0.5.3
  audioplayers: 0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # 图片
    - images/bg1.jpg
    - images/bg2.jpg
    - images/player_bullet1.png
    - images/player_bullet2.png
    - images/player_bullet3.png
    - images/enemy01.png
    - images/enemy02.png
    - images/enemy03.png
    - images/player_state1.png
    - images/player_state2.png
    - images/player_state3.png
    - images/player_state4.png
    - images/boom_state1.png
    - images/boom_state2.png
    - images/boom_state3.png
    - images/boom_state4.png
    - images/home_bg1.jpg
    - images/home_bg2.jpg
    - images/home_bg3.jpg
    - images/home_bg4.jpg
    - images/home_bg5.jpg
    - images/home_bg6.jpg
    - images/home_bg7.jpg
    - images/home_bg8.jpg
    - images/home_bg9.jpg
    - images/home_bg10.jpg
    - images/home_bg11.jpg
    - images/home_bg12.jpg
    - images/home_bg13.jpg
    - images/home_bg14.jpg
    - images/home_bg15.jpg
    - images/home_bg16.jpg
    - images/home_bg17.jpg
    - images/home_bg18.jpg
    - images/home_bg19.jpg
    - images/home_bg20.jpg
    - images/btn.png
    - images/pause.png
    - images/rocket_01.png
    - images/rocket_02.png
    - images/rocket_03.png
    # 音效
    - assets/game_bg.mp3
    - assets/home_bg.mp3
    - assets/player_bullet.wav
    - assets/enemy_boom01.mp3
    - assets/enemy_boom02.mp3
    - assets/enemy_boom03.mp3

  fonts:
    - family: AppFont
      fonts:
        - asset: fonts/font.ttf